### ISSUE TITLE
Multiple Data Sources Not Working

### ISSUE THREAD

**Issue by alcidesfp** [fzilic/Grails-MyBatis#11]
I've been sucessfully using this plugin in production environment for some months.
Now we have a new requirement as part of which we have to use more than one database, hence, we need to configure and use more than one datasource.
I've been trying to use the plugin with multiple datasources as shown in the source code examples but apparently there is a missing step and the DataGateways dont get the different data sources.

**Comment by fzilic** [comment]
Have you tried adding this field `def static dataSourceName = 'dataSource'` to your Gateway 

There is a sample file in documentation, but I haven't mentioned it in main documentation body. It has to be fixed in documentation if it works.

Last time I tested it it worked fine.

**Comment by alcidesfp** [comment]
Yes, I've done that too.. and still not working...
I have defined in my DataSource.groovy the following: 

``` groovy
dataSource {
    pooled = true
    jmxExport = true
    driverClassName = "org.postgresql.Driver"
    username="alcides"
    password="asdf1"
    ...
}

dataSource_2 {
    pooled = true
    jmxExport = true
    driverClassName = "org.postgresql.Driver"
    username="alcides"
    password="asdf2"
    ...
}
```

I have two data gateways, one of them using the second data source (dataSource_2):

```
class Contacto2Gateway {
    def static dataSourceName = 'dataSource_2'
}
```

And get this error:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'sqlSessionTemplate_dataSource_2' is defined
    at org.grails.plugins.mybatis.MappingSupport.invokeMybatis(MappingSupport.groovy:64)
    at org.grails.plugins.mybatis.MappingSupport.registerMappings_closure2_closure7_closure9(MappingSupport.groovy:99)
    at directorio.Contacto2GatewayTestSpec.Prueba DataGateway2(Contacto2GatewayTestSpec.groovy:35)
```

**Comment by fzilic** [comment]
I'm sorry for not coming back to you earlier.

Try adding this line to your DataSource.groovy configuration file:

``` groovy
mybatis.dataSourceNames = ['dataSource', 'dataSource_2']
```

**Comment by fzilic** [comment]
@alcidesfp I have just checked the docs, in chapter **2 Getting Started** there is an section **DataSource configuration** which describes this property.

It might not be as clear as it could be.

**Comment by alcidesfp** [comment]
Thank you very much!! Its working now for me..

**Comment by fzilic** [comment]
Thank you for all the support and contributions.
