### ISSUE TITLE
XML files not in WAR 

### ISSUE THREAD

**Issue by alcidesfp** [fzilic/Grails-MyBatis#8]
By default XML resources (mapping files) are NOT being included in the user's project generated WAR.
IMHO on installation, this plugin should inject a "scripts/_Events.groovy" file in the user's project with all the needed instructions to do this. Removing the need to manually add them to the user's project BuildConfig.groovy

**Comment by fzilic** [comment]
Now that you mention it, I remember we had that problem, but it didn't get included in this plugin.
You can submit a pull request if you wish, or I can code it myself.

**Comment by alcidesfp** [comment]
Hello Franjo

As you suggested, I have already submited a pull request that fixes a
couple of issues including this one (details in Github)
Thank you very much for your response and for creating this plugin.

Greetings.
--
Alcides Flores Pineda

2015-06-10 1:17 GMT-05:00 Franjo Žilić <notifications@github.com>:

**Comment by fzilic** [comment]
I've managed to find time and update plugin.
Some of the changes broke Grails 2.0.x support, but it should be working right now.
